name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          for o in ${{ steps.files.outputs.added_modified }}; do
            if [[ "$o" == *.cls ]]
            then
              echo "$o is a class"
              if test -f "${o/.cls/Test.cls}";
              then
                echo "$o has a test class"
              fi
            else
              echo "$o is not a class"
            fi
          done
          echo "All:"
          echo "${{ steps.files.outputs.all }}"
          echo "Added:"
          echo "${{ steps.files.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.files.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.files.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.files.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.files.outputs.added_modified }}"