name: Say Hello World
on:
  issues:
    types:
      - opened
permissions:
  issues: write
  pull-requests: write
  statuses: write
  checks: write
jobs:
  sayHelloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: probot/example-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}