name: Code Quality Scan
on:
  pull_request:
    branches:
      - main
      - next


jobs:
  sfdx-code-scan:
    name: Apex Code Quality
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Code Review
        uses: brentgorton/sfdx-code-review-action@annotations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            source_path: '"***.cls" "***.trigger" "***.js" "***.html" "***.page" "***.cmp" "***.component"'
            reject_threshold: 1
            max_comments: 20
            engine: 'pmd'
            dfa_setting: ''
            github_token: ${{ secrets.GITHUB_TOKEN }}
            projectdir: 'sfdx-src'