name: Code Quality Scan
on:
  pull_request:
    branches:
      - main
      - next
permissions:
  checks: write
  contents: write
  pull-requests: read

jobs:
  sfdx-code-scan:
    name: Apex Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Code Review
        uses: brentgorton/sfdx-code-review-action@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
            source_path: '"***.cls" "***.trigger" "***.js" "***.html" "***.page" "***.cmp" "***.component"'
            reject_threshold: 1
            max_comments: 20
            engine: 'pmd'
            dfa_setting: ''
            github_token: ${{ secrets.GH_TOKEN }}
            projectdir: 'sfdx-src'